name: geocat-applications
channels:
  - conda-forge
dependencies:
  - cartopy
  - geocat-datafiles
  - matplotlib
  - netcdf4
  - numpy
  - pre-commit
  - python
  - xarray
  - ipykernel
  - ipython
  - jupyter_client
  - matplotlib-base
  - sphinx-book-theme
  - myst-nb
  - sphinx-design
  - sphinxcontrib-bibtex
  - nbsphinx
  - pandas
